config/routes.rb
Rails.application.routes.draw do

resources :requests

get "/search"           => "requests#search"

root "requests#index"

end

app/models/request.rb
class Request < ActiveRecord::Base

  validates :name, presence: {message: "must be provided"}

  validates :email, presence: {message: "must be provided"}

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/requests_controller.rb
class RequestsController < ApplicationController

  def index

    @requests = Request.all.order("action DESC")
    

  end

  def new

    @request = Request.new

  end

  def create

    @request = Request.new(params.require(:request).permit(:name, :email, :department, :message, :action))

    #@request.action = "Not Done"


    if @request.action == "1"
      @request.action = "Done"  
    else
      @request.action = "Not Done"
    end

      

    if @request.save
      redirect_to requests_path
    else
      render :new
    end

  end

  def show

    @request = Request.find(params[:id])

  end

  def edit

    @request = Request.find(params[:id])  

  end

  def update

    @request = Request.find(params[:id])
    if @request.update_attributes(params.require(:request).permit(:name, :email, :department, :message, :action))
      if @request.action == "1"
        @request.action = "Done"  
      else
        @request.action = "Not Done"
      end
      @request.save
      redirect_to requests_path
    else
      flash.now[:alert] = "There was a problem updating yor form"
    end

  end

  def destroy

    @request = Request.find(params[:id])
    @request.destroy
    flash[:alert] = "Request was deleted successfully"
    redirect_to requests_path

  end

  def search

    #@query = params[:query]
    @zero_result = "Couldn't find any results"
    #@result_array = []

    @requests = Request.where("name LIKE ? OR email LIKE ? OR message LIKE ? ", params[:query], params[:query], params[:query]).paginate(:page => params[:page], :per_page => 1)

  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/requests_helper.rb
module RequestsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>SuportRequests</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

  <nav class="nav navbar-default">
    <div class="container-fluid">
      <ul class="nav navbar-nav">
        <li><%= link_to "Home", root_path %></li>
        <li><%= link_to "Create new Request", new_request_path %></li>
      </ul>
    </div>
  </nav>


<div class="container">
  <%= yield %>
</div>

</body>
</html>

app/views/requests/_form.html.erb
<%= form_for @request do |f| %>
  
  <div class="form-group">
    <%= f.label :name %>
    <%= f.text_field :name, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= f.label :email %>
    <%= f.text_field :email, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= f.radio_button(:department, "sales") %>
    <%= f.label(:department, "Sales") %>
    <%= f.radio_button(:department, "marketing") %>
    <%= f.label(:department, "Marketing") %>
    <%= f.radio_button(:department, "technical") %>
    <%= f.label(:department, "Technical") %>
  </div>

  <div class="form-group">
  <%= f.label :message %>
  <%= f.text_area :message, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= f.check_box(:action) %>
    <%= f.label(:action, "Not Done") %>
    <%= f.check_box(:action) %>
    <%= f.label(:action, "Done") %>
  </div>

  <%= f.submit class: "btn btn-primary" %>

  <% end %>

app/views/requests/edit.html.erb
<%= render "form" %>

app/views/requests/index.html.erb
<h1>Support Request Tool</h1>

    <div class="new-request-button">
      <%= link_to "Create new Request", new_request_path, class: "btn btn-success" %>
    </div>

     <div class="search-button">
      <%= form_tag("/search", method: "get") do %>
      <%= label_tag(:query, "Search for:") %>
      <%= text_field_tag(:query) %>
      <%= submit_tag("Search") %>
      <% end %>
    </div> 

  
    <table class="table table-bordered">
        <tr>
          <th>Name</th>
          <th>Email</th>
          <th>Department</th>
          <th>Message</th>
          <th>Action</th>
        </tr>
        <% @requests.each do |request| %>
      
        <tr>  
          <td><p><%= link_to request.name, request_path(request) %></p></td>
          <td><%= mail_to request.email %></td>
          <td><%= request.department %></td>
          <td><%= request.message %></td>
          <td><%= link_to "Edit", edit_request_path(request), class: "btn btn-primary" %> <%= link_to "Delete", @request, method: :delete, data: {confirm: "Are you sure you want to delete this request?"}, class: "btn btn-danger" %> <%= request.action %></td>
        </tr>  
        <% end %>  
    </table>   

app/views/requests/new.html.erb
<h1>Create new Request</h1>

<%= render "form" %>

<% @request.errors.full_messages.each do |error| %>
  <%= error %>
  <br>

<% end %>

app/views/requests/search.html.erb
<h1>Search Results</h1>

<table class="table table-bordered">
 <tr>
  <th>Name</th>
  <th>Email</th>
  <th>Message</th>
  <th>Department</th>
  <th>Action</th>
 </tr>

  <% if @requests != [] %>
    <% @requests.each do |request| %>
      <tr>
        <td><%= request.name %></td>
        <td><%= request.email %></td>
        <td><%= request.message %></td>
        <td><%= request.department %></td>
        <td><%= request.action %></td>
      </tr>
    <% end %>
  <% else %>
    <%= @zero_result %>
  <% end %>

</table>

<div class="pagination">
  <%= will_paginate @requests %>
</div>

app/views/requests/show.html.erb
<h2><%= @request.name %></h2>
<p><%= @request.email %></p>
<p><%= @request.department %></p>
<p><%= @request.message %></p>
<p><%= @request.action %></p>

<%= link_to "Edit", edit_request_path(@request), class: "btn btn-primary" %>

<%= link_to "Delete", @request, method: :delete, data: {confirm: "Are you sure you want to delete this request?"}, class: "btn btn-danger" %>